name: MSBuild

on:
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore Win32
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=Win32 .

      - name: Restore x64
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL Win32
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build DLL x64
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL ARM64X
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=ARM64EC .

      - name: Build Config
        run: msbuild -m -target:VietTypeConfig2:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build Win32
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build x64
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build ARM64X
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=ARM64EC .

      - name: Upload a Build Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: VietTypeSetup/bin/
          name: VietType_App

    outputs:
      subject-name: VietType_App
      subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
