name: MSBuild

on:
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: .

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore Win32
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=Win32 .

      - name: Restore x64
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL Win32
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build DLL x64
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build Config
        run: msbuild -m -target:VietTypeConfig2:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build Win32
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build x64
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Upload a Build Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: VietTypeSetup/bin/
          name: artifact.zip

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: artifact.zip
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
