name: test

on: [push]

env:
  SOLUTION_FILE_PATH: .

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        platform:
          - Win32
          - x64

    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1.1.1

      - name: Build unit tests
        run: msbuild.exe -m -target:VietTypeUnitTests:Rebuild -p:Configuration=${{matrix.configuration}} -p:Platform=${{matrix.platform}} .

      - name: Run tests
        run: vstest.console.exe ${{matrix.platform}}/${{matrix.configuration}}/VietTypeUnitTests.dll
