name: test

on: [push]

env:
  SOLUTION_FILE_PATH: .

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        platform:
          - Win32
          - x64

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup VSTest.console.exe
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $vs = & "${Env:ProgramFiles(x86)}/Microsoft Visual Studio/Installer/vswhere.exe" -latest -property installationPath
          Add-Content $Env:GITHUB_PATH "$vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow"

      - name: Build unit tests
        run: msbuild.exe -m -target:VietTypeUnitTests:Rebuild -p:Configuration=${{matrix.configuration}} -p:Platform=${{matrix.platform}} .

      - name: Run tests
        run: vstest.console.exe ${{matrix.platform}}/${{matrix.configuration}}/VietTypeUnitTests.dll
